export type HeaderCopyBank = "quotes" | "sceptic" | "jokes" | "qotd";

export const HEADER_COPY_BANKS: HeaderCopyBank[] = ["quotes", "sceptic", "jokes", "qotd"];

export function isHeaderCopyBank(id: string): id is HeaderCopyBank {
  return HEADER_COPY_BANKS.includes(id as HeaderCopyBank);
}

export const HEADER_COPY: Record<HeaderCopyBank, string[]> = {
  quotes: [
    "Start before you feel ready. Ready is a story you tell after you begin.",
    "Small steps still count as movement. Keep the line going.",
    "You do not need a perfect morning. You need the next honest try.",
    "Progress is quiet. It looks like showing up again.",
    "The hard part is starting. The next part is just continuing.",
    "Be kind to the person you are becoming. They are watching how you treat today.",
    "A tidy win is still a win. Take it.",
    "You can do a hard thing slowly. Slow still finishes.",
    "Today is not asking for a masterpiece. It is asking for effort.",
    "Put your name on one good decision before lunch.",
    "Courage is often just a smaller fear plus a deadline.",
    "Leave the day better than you found it, even by an inch.",
    "Your future self is not magical. They are you, with more reps.",
    "If it matters, give it ten focused minutes.",
    "Rest is part of the plan, not a leak in it.",
    "You already survived every yesterday. Use that data.",
    "Make the next hour useful. The week will follow.",
    "A calm voice can still be a brave one.",
    "Do the boring bit. That is where the results hide.",
    "You are allowed to begin again at 3pm.",
    "Keep promises to yourself in public-size font.",
    "Less drama, more drafts. Ship the next version.",
    "Energy follows action more often than the reverse.",
    "Choose the option you will be proud to describe tonight.",
    "The mountain is climbed by people who packed water.",
    "Be the teammate your household can rely on.",
    "A good mood can be built, not waited for.",
    "Finish one loop. Open the next with cleaner hands.",
    "Your standards can be high without being cruel.",
    "Talk to yourself like someone you are coaching, not scolding.",
    "The work is the path. The path is enough for today.",
    "Collect tiny proofs that you can follow through.",
    "You do not have to feel inspired to be useful.",
    "Protect the first hour. It teaches the rest of the day manners.",
    "If you stall, shrink the task until it moves.",
    "Let done be the cousin of excellent, not the enemy.",
    "A walk can reset more than a spiral ever will.",
    "Stay with the problem one layer longer than comfort.",
    "Your attention is a tool. Point it on purpose.",
    "Make room for joy without waiting for a trophy.",
    "The family needs your steady, not your perfect.",
    "Build a morning you would recommend to a friend.",
    "When in doubt, tidy one corner and begin.",
    "You can be tired and still be trustworthy.",
    "Write the next sentence. Life is a stack of those.",
    "Hope works better when it has a checklist.",
    "Be stubborn about kindness, especially inward.",
    "Today's job is to reduce tomorrow's friction.",
    "A brave minute beats a worried hour.",
    "Keep your humour. It is a form of stamina.",
    "You are not behind. You are in the middle of the story.",
    "Choose water, daylight, and one hard yes.",
    "Make the kind choice, then the useful one.",
    "Your pace can be human and still be ambitious.",
    "Show the work. Hide the spiral.",
    "A closed loop is a gift to future-you.",
    "Let curiosity outrun embarrassment.",
    "You can change the plan without changing the aim.",
    "Practice being someone who returns to the task.",
    "The win is often just not quitting at the ugly bit.",
    "Give today a theme: finish, mend, or begin.",
    "Your body is not a project. It is the team.",
    "Speak the goal out loud. It behaves better in daylight.",
    "If it is worth doing, it is worth doing at 70%.",
    "A clear no protects a better yes.",
    "Leave breadcrumbs of progress so tomorrow can find them.",
    "Be proud of the unglamorous maintenance.",
    "The next kind act can be toward your own inbox.",
    "You grow by repeating the unremarkable well.",
    "Make the kitchen, the plan, or the mood a little lighter.",
    "Hold the line on sleep. Everything else borrows from it.",
    "A good question is already half the work.",
    "You can ask for help and still be strong.",
    "Treat friction as information, not a verdict.",
    "Put your phone down for one real conversation.",
    "The day improves when someone decides it will.",
    "Keep a short list and a long patience.",
    "Your effort is not wasted if it taught you the map.",
    "Be the weather you want in the house.",
    "Start with the thing that unsticks the rest.",
    "A smile you mean is still a form of leadership.",
    "Do not wait for permission to take care of the basics.",
    "You can be unfinished and still be moving right.",
    "Make excellence ordinary: same time, same chair, same try.",
    "The best pep talk is a glass of water and a first step.",
    "Let today's version be slightly braver than yesterday's.",
    "Carry the load you can, then share the rest.",
    "A clean table can change the next hour's odds.",
    "You are building a reputation with yourself. Make it kind.",
    "When the plan breaks, write a smaller one.",
    "Stay curious about how this could work.",
    "The goal is not to impress the clock. It is to use it.",
    "Give credit to the quiet days. They compound.",
    "Be generous with second chances, starting with you.",
    "A habit is just a decision that got tired of debating.",
    "Put music on if it helps. Put the task on either way.",
    "You can outlast a bad morning. Afternoons exist.",
    "Choose the story where you are capable and still learning.",
    "Make one thing easier for the people you love.",
    "Keep going. The plot usually improves after the slog.",
    "Your best is a moving target. Aim at today's best.",
    "Let the work be simple: show up, stay, finish a piece.",
    "A little order now saves a lot of apology later.",
    "You do not need a new personality. You need a next action.",
    "Be loyal to the plan for one more hour.",
    "The world is heavy. Add one useful lightness.",
    "Name the win before you hunt the next problem.",
    "You are allowed to be proud of ordinary competence.",
    "If it scares you a bit and helps someone, lean in.",
    "Keep your word in small things. Large things notice.",
    "Today can still turn. Turn it.",
  ],
  sceptic: [
    "If a god is all-good and all-powerful, pointless suffering still needs a better answer.",
    "Hiddenness is odd: a loving parent does not stay permanently unfindable.",
    "Occam prefers fewer invisible agents when nature already explains the weather.",
    "Evolution accounts for eyes and immune systems without a draftsman.",
    "Unanswered prayer looks like chance plus memory bias, not a switchboard.",
    "Goalposts move from 'prove God' to 'you cannot disprove my private feeling'.",
    "The burden of proof sits with the extraordinary claim, not the shrug.",
    "Revelations disagree by region. Geography is a poor oracle.",
    "Omniscience plus libertarian free will is a knot, not a mystery we must praise.",
    "Holy books look like their centuries: bronze-age law, not cosmic footnotes.",
    "A designer who needs parasites and childhood cancer is a hard sell as love.",
    "If miracles were reliable, hospitals would publish them like drug trials.",
    "Moral progress often happens against scripture, not because of it.",
    "Hell as infinite payback for finite doubt is justice only on a poster.",
    "Faith that forbids exit is indistinguishable from a locked room.",
    "Natural disasters do not aim. That is the kinder reading.",
    "Many gods were once obvious. Most are now folklore. Pattern noted.",
    "A universe that looks undesigned at the edges looks undesigned at the centre too.",
    "If conscience is implanted, it is strangely tribal and trainable.",
    "Silence after tragedy is evidence, not a test we failed by noticing.",
    "First-cause arguments stall: special pleading is not an explanation.",
    "Fine-tuning talk often ignores selection: we only ask from habitable rooms.",
    "Personal revelation is private data. It does not bind the rest of us.",
    "If God wants belief, ambiguity is a strange teaching method.",
    "Scripture's science tracks the sky of its authors, not later telescopes.",
    "Animal pain predates humans. A fall-from-Eden story arrives late.",
    "Competing churches cannot all be uniquely guided by the same mind.",
    "Prayer studies keep looking like regression to the mean.",
    "A god beyond evidence is a god beyond being distinguished from absence.",
    "Divine command theory makes goodness a mood of power, not a reason.",
    "If mystery is the reply to every hard question, it is not a reply.",
    "Prophecy after the fact is easy. Named dates before the fact are rare.",
    "Souls that leave no trace behave like stories we prefer to keep.",
    "The problem of divine hiddenness is not solved by calling doubt a vice.",
    "A watch on a heath is not a cell. Biology copies, it does not engrave.",
    "If worship is required, the relationship already looks one-sided.",
    "Miracles cluster in poorly documented times. That is a clue.",
    "Omnibenevolence plus eternal torment is a contradiction with extra steps.",
    "We excuse a god for acts we would jail a human for. Inconsistency check.",
    "Sacred texts edit, redact, and argue. That is human literature.",
    "If God is perfectly hidden, atheism is the rational default, not a tantrum.",
    "Complexity of life is not complexity of authorship. Snowflakes are not carved.",
    "Moral luck and birthplace predict creed better than cosmic truth does.",
    "A plan that requires deniability is not a plan that wants to be known.",
    "Unfalsifiable claims are safe from error and also safe from knowledge.",
    "The universe is large, old, and mostly empty. That is an odd nursery.",
    "If God speaks, the signal-to-noise ratio looks like human noise.",
    "Suffering of the innocent is not made holy by calling it a lesson.",
    "Gods shrink as explanations grow: lightning, disease, orbits, genes.",
    "A being who needs praise has the psychology of a court, not a cosmos.",
    "Free-will defences stumble on natural evil: no human chose the quake.",
    "If all religions can be wrong, yours can be too. Apply evenly.",
    "Experience of awe is real. The inference to a monarch is extra.",
    "Anselm's greatest being is a word game unless existence is a predicate. It is not.",
    "Pascal's wager forgets the other wagers and the cost of false belief.",
    "If God is outside time, 'answering' prayer needs a story, not a slogan.",
    "Scriptural slavery clauses age poorly if they were meant as last words.",
    "A loving law would not hinge salvation on accident of catechism.",
    "The more a claim is insulated from revision, the less it can learn.",
    "Mind is what brains do. Damage the brain, change the 'soul'.",
    "If God is perfectly good, creating avoidable agony needs a ledger we never see.",
    "Hiddenness plus hell is a trap, not a pedagogy.",
    "We do not grant other ancient cosmologies a free pass. Consistency, please.",
    "Design arguments undercount waste: most species are gone, most space is lethal.",
    "A god who cannot be tested cannot be told apart from our hopes.",
    "Religious certainty often tracks upbringing, not a worldwide audit.",
    "If prayer works like placebo, that is still interesting and still not a deity.",
    "Omnipotence that cannot prevent a holocaust is a redefinition, not a rescue.",
    "Texts that threaten doubt are advertising, not epistemology.",
    "The cosmological argument names a stop. Naming is not knowing.",
    "If morality needs a god, we still had to judge that god's commands first.",
    "Many sincere people report opposite revelations. Sincerity is not a method.",
    "A world run by regularities does not need a manager for each sparrow.",
    "The 'god of the gaps' retreats. Retreat is a map of our ignorance.",
    "If faith is trust without evidence, it is also available to every rival creed.",
    "Euthyphro still stands: good because commanded, or commanded because good?",
    "Childhood indoctrination is efficient. That does not make it true.",
    "A creator who values belief over compassion has odd priorities.",
    "We explain cargo cults without gods. Apply the same charity inward.",
    "If souls wait for ensoulment stories, biology was doing fine already.",
    "Divine justice delayed forever is not distinguishable from no justice.",
    "The quieter hypothesis: nobody is listening, and we still have each other.",
    "Inconsistent attributes are not deepened by calling them paradox.",
    "If God is simple, the trinity and theodicy are not. Pick a lane.",
    "Historical religions look like politics with incense. Read the minutes.",
    "A miracle that violates nature and leaves no residue is a rumour.",
    "We should not lower the bar for God below the bar for a court case.",
    "If meaning requires eternity, a sunset was never enough. That seems unkind.",
    "The argument from beauty forgets that beauty is a brain's taste, not a proof.",
    "People recover without prayer and suffer with it. The scatter looks natural.",
    "A hidden god who punishes honest inquiry has authored a cruel exam.",
    "Explanations that work everywhere else should work on origins too.",
    "If God is love, the body count in the old stories needs a rewrite or a reject.",
    "We can be grateful for life without inventing a landlord.",
    "Doubt is not a moral failure. It is quality control.",
    "When every outcome is 'God's will', the word will has left the building.",
    "A hypothesis that fits every result predicts none.",
    "Sacred immunity from critique is a social privilege, not a truth-maker.",
    "If minds need brains, disembodied mind is a further, costlier claim.",
    "The simplest reading of the sky is that it does not owe us a parent.",
    "Civil disagreement is allowed. So is noticing the arguments do not land.",
    "We can respect people and still decline their invisible monarch.",
    "A good life does not require a cosmic audience. The family is enough.",
    "If God hides to protect freedom, evidence-based medicine should ruin virtue too.",
    "The map of belief matches missionaries and empires more than telescopes.",
    "An all-knowing planner who uses mystery as a shield is asking for less scrutiny.",
    "We outgrew local spirits. The last spirit is not special by being last.",
    "Suffering distributed at random is what a godless world already predicts.",
    "If revelation were clear, heresy trials would have been shorter.",
    "Keep the poetry. Retire the metaphysics that cannot pay its way.",
    "Absence of evidence is not proof, but after a long search it is a hint.",
    "A civil no is still a no: the case for gods remains unfinished.",
  ],
  jokes: [
    "I told my suitcase there would be no more trips. Now it is packed with emotion.",
    "Why did the scarecrow get promoted? He was outstanding in his field.",
    "I would tell you a construction joke, but I am still working on it.",
    "What do you call a bear with no teeth? A gummy bear.",
    "I used to hate facial hair, but then it grew on me.",
    "Why don't eggs tell jokes? They would crack each other up.",
    "I am reading a book on anti-gravity. It is impossible to put down.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "I asked for books on paranoia. The librarian whispered, they're right behind you.",
    "Why did the coffee file a police report? It got mugged.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "What do you call a fake noodle? An impasta.",
    "I tried to catch fog yesterday. I mist.",
    "Why was the maths book sad? It had too many problems.",
    "I used to be a baker, but I did not have enough dough.",
    "What do you call cheese that is not yours? Nacho cheese.",
    "I told my computer I needed a break, and it said no problem, it had a crash course.",
    "Why did the bicycle fall over? It was two-tired.",
    "I am on a seafood diet. I see food and I eat it.",
    "What do you call a sleeping bull? A bulldozer.",
    "I would tell a joke about pizza, but it is a little cheesy.",
    "Why can't you hear a pterodactyl go to the loo? The p is silent.",
    "I named my dog Five Miles so I can say I walk Five Miles every day.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "I stayed up all night to see where the sun went. Then it dawned on me.",
    "Why did the golfer bring two pairs of trousers? In case he got a hole in one.",
    "I used to play piano by ear, but now I use my hands.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "I asked my dog what's two minus two. He said nothing.",
    "Why did the cookie go to the doctor? It felt crummy.",
    "I don't trust stairs. They are always up to something.",
    "What do you call a fish with no eyes? A fsh.",
    "I told a joke about a roof. It went over everyone's head.",
    "Why are ghosts bad at lying? You can see right through them.",
    "I used to be addicted to the hokey cokey, but I turned myself around.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "I have a joke about time travel, but you didn't like it.",
    "Why did the tomato blush? It saw the salad dressing.",
    "I wanted to be a baker, then I realised I kneaded more practice.",
    "What do you call an alligator in a vest? An investigator.",
    "I tried to write a joke about sheets, but it was too cover-y.",
    "Why don't scientists trust atoms? They make up everything.",
    "I bought a thesaurus, but I could not find the words to describe how happy I was.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "I used to be a tailor, but I wasn't suited to it.",
    "Why did the stadium get hot after the game? All the fans left.",
    "I have a fear of speed bumps, but I am slowly getting over it.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I told my plants a joke. They didn't laugh, they just photosynthesized.",
    "Why did the belt go to jail? It held up a pair of trousers.",
    "I can't take my dog to the pond anymore. The ducks keep billing him.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "I used to hate organic chemistry, but carbon really bonded with me.",
    "Why did the chicken join a band? It had the drumsticks.",
    "I asked the gym if they could teach me to do the splits. They said it was a stretch.",
    "What do you call a pig that knows karate? A pork chop.",
    "I only tell lighthouse jokes. They are always a beacon of hope.",
    "Why don't oysters donate to charity? Because they are shellfish.",
    "I accidentally swallowed some food colouring. I feel like I've dyed a little inside.",
    "What did the left eye say to the right eye? Between us, something smells.",
    "I used to be indecisive. Now I am not sure.",
    "Why did the calendar get in trouble? It had too many dates.",
    "I have a joke about UDP, but I don't know if you'll get it.",
    "What do you call a parade of rabbits hopping backwards? A receding hare-line.",
    "I told my Wi-Fi we needed space. Now I have connection issues.",
    "Why did the banana go to the doctor? It wasn't peeling well.",
    "I started a band called 1023MB. We haven't got a gig yet.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "I used to run a dating service for chickens, but I was struggling to make hens meet.",
    "Why can't your nose be 12 inches long? Because then it would be a foot.",
    "I have a joke about paper, but it is tearable.",
    "What did one plate say to the other? Lunch is on me.",
    "I tried to write with a broken pencil. It was pointless from the start.",
    "Why did the man fall down the well? He couldn't see that well.",
    "I used to be a banker, but I lost interest.",
    "What do you call a can opener that doesn't work? A can't opener.",
    "I told a chemistry joke. There was no reaction.",
    "Why did the cookie cry? Because its mother had been a wafer so long.",
    "I have a joke about erasers, but it will be rubbed out soon.",
    "What do you call a cow with no legs? Ground beef.",
    "I asked for books on turtles. She said they were a hard shell to find.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to be a wrestler, but I had to throw in the towel.",
    "What did the buffalo say to his son when he left? Bison.",
    "I have a joke about scaffolding. It is supporting material only.",
    "Why was the broom late? It overswept.",
    "I told my shoes a secret. They were loafers, so they didn't run with it.",
    "What do you call a sad strawberry? A blueberry.",
    "I used to play with airplanes as a kid. I was outstanding in my runway.",
    "Why did the invisible man turn down the job offer? He just couldn't see himself doing it.",
    "I have a joke about the fridge, but it is a bit chilled.",
    "What do you call a bee that can't make up its mind? A maybe.",
    "I tried to be a firefighter, but I flamed out. Then I retired to dad jokes.",
    "Why did the mushroom go to the party? Because he was a fun-gi.",
    "I have a joke about elevators, but it has its ups and downs.",
    "What did the clock do when it was hungry? It went back four seconds.",
    "I used to be a gardener, but I didn't have the thyme.",
    "Why did the computer go to therapy? It had too many bytes of emotional baggage.",
    "I told the window a joke. It was a pane to explain.",
    "What do you call a group of musical whales? An orca-stra.",
    "I have a joke about butter, but I am on a roll.",
    "Why don't mountain climbers make good secret agents? They always peak.",
    "I used to collect cans, but it was soda pressing.",
    "What did the hat say to the scarf? You hang around, I'll go on ahead.",
    "I have a joke about unfinished sentences",
    "Why did the soccer ball go to school? To get a little kick out of education.",
    "I asked my diary if it was okay. It said it was bound to be fine.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "I have a joke about shadows, but it is following me.",
    "Why did the crayon quit? It was drawn to something else.",
    "I used to be a baker of puns. Now I just loaf around and prove it.",
    "What do you call an owl that does magic? Hoodini.",
    "I have a joke about silence. ...",
    "Why did the sandwich go to the therapist? It felt spread too thin.",
  ],
  qotd: [
    "We suffer more often in imagination than in reality. — Seneca",
    "Luck is what happens when preparation meets opportunity. — Seneca",
    "It is not that we have a short time, but that we waste much of it. — Seneca",
    "If a man knows not which port he sails, no wind is favourable. — Seneca",
    "Associate with people who improve you. — Seneca",
    "Begin at once to live, and count each day as a separate life. — Seneca",
    "The greatest remedy for anger is delay. — Seneca",
    "He who is brave is free. — Seneca",
    "You are scared of dying, and tell me, is the kind of life you lead any different? — Seneca",
    "While we wait for life, life passes. — Seneca",
    "Waste no more time arguing what a good man should be. Be one. — Marcus Aurelius",
    "The impediment to action advances action. What stands in the way becomes the way.",
    "You have power over your mind, not outside events. Realise this, and find strength.",
    "The happiness of your life depends upon the quality of your thoughts. — Aurelius",
    "When you arise in the morning, think of what a privilege it is to be alive. — Aurelius",
    "Accept the things to which fate binds you, and love the people with whom fate brings you.",
    "Very little is needed to make a happy life. — Marcus Aurelius",
    "The best revenge is not to be like your enemy. — Marcus Aurelius",
    "Do not act as if you were going to live ten thousand years. — Marcus Aurelius",
    "If it is not right, do not do it. If it is not true, do not say it. — Aurelius",
    "A room without books is like a body without a soul. — Cicero",
    "The unexamined life is not worth living. — Socrates",
    "Know thyself. — Delphic maxim",
    "Nothing in excess. — Delphic maxim",
    "Time is the most valuable thing a man can spend. — Theophrastus",
    "No man ever steps in the same river twice. — Heraclitus",
    "Character is destiny. — Heraclitus",
    "The only true wisdom is in knowing you know nothing. — Socrates",
    "Fortune favours the bold. — Latin proverb",
    "A rolling stone gathers no moss. — Public-domain proverb",
    "Slow and steady wins the race. — After Aesop",
    "Honesty is the best policy. — Public-domain proverb",
    "A stitch in time saves nine. — Proverb",
    "Look before you leap. — Proverb",
    "Make hay while the sun shines. — Proverb",
    "Still waters run deep. — Proverb",
    "The early bird catches the worm. — Proverb",
    "Where there is a will, there is a way. — Proverb",
    "Actions speak louder than words. — Proverb",
    "Better a little with peace than much with trouble. — After Proverbs",
    "Pride goes before a fall. — After Proverbs",
    "A soft answer turns away wrath. — After Proverbs",
    "Train up a child in the way he should go. — After Proverbs",
    "To everything there is a season. — After Ecclesiastes",
    "What has been will be again. There is nothing new under the sun. — Ecclesiastes",
    "Better is a dinner of herbs where love is. — After Proverbs",
    "He that is slow to anger is better than the mighty. — After Proverbs",
    "Hope deferred makes the heart sick. — After Proverbs",
    "A merry heart does good like a medicine. — After Proverbs",
    "Do not boast about tomorrow, for you do not know what a day may bring.",
    "Enough is as good as a feast. — Proverb",
    "Many hands make light work. — Proverb",
    "Waste not, want not. — Proverb",
    "Well begun is half done. — Proverb",
    "Two heads are better than one. — Proverb",
    "A friend in need is a friend indeed. — Proverb",
    "Birds of a feather flock together. — Proverb",
    "Every cloud has a silver lining. — Proverb",
    "All that glitters is not gold. — Proverb",
    "Practice what you preach. — Proverb",
    "Rome was not built in a day. — Proverb",
    "When in Rome, do as the Romans do. — Proverb",
    "The pen is mightier than the sword. — After Bulwer-Lytton, now proverb",
    "Knowledge is power. — After Bacon, now proverb",
    "To be, or not to be, is less useful than: what will you do before lunch?",
    "An investment in knowledge pays the best interest. — After Franklin",
    "Early to bed and early to rise, makes a man healthy, wealthy, and wise. — Franklin",
    "Well done is better than well said. — Benjamin Franklin",
    "Lost time is never found again. — Franklin",
    "He that can have patience can have what he will. — Franklin",
    "Diligence is the mother of good luck. — Franklin",
    "Never leave that till tomorrow which you can do today. — Franklin",
    "A penny saved is a penny earned. — After Franklin",
    "By failing to prepare, you are preparing to fail. — After Franklin",
    "Be at war with your vices, at peace with your neighbours. — Franklin",
    "The doors of wisdom are never shut. — Franklin",
    "Little strokes fell great oaks. — Franklin",
    "No gains without pains. — Franklin",
    "God helps them that help themselves is folk wisdom, not a grant application.",
    "Moderation in all things. — After Aristotle, now proverb",
    "We are what we repeatedly do. Excellence, then, is habit. — After Aristotle",
    "Happiness depends upon ourselves. — Aristotle",
    "The more you know, the more you realise you do not know. — After Aristotle",
    "Patience is bitter, but its fruit is sweet. — After Rousseau, proverb form",
    "Do what you can, with what you have, where you are. — After Roosevelt, short form",
    "The journey of a thousand miles begins with a single step. — After Laozi",
    "Those who know do not boast. Those who boast do not know. — After Laozi",
    "Nature does not hurry, yet everything is accomplished. — After Laozi",
    "A good traveller has no fixed plans and is not intent on arriving. — After Laozi",
    "The wise find pleasure in water; the virtuous find pleasure in hills. — Confucius",
    "Is it not a joy to have friends come from afar? — Confucius",
    "When we see men of worth, we should think of equalling them. — Confucius",
    "The superior man is modest in his speech, but exceeds in his actions. — Confucius",
    "To see what is right and not do it is want of courage. — Confucius",
    "Real knowledge is to know the extent of one's ignorance. — Confucius",
    "Silence is a true friend who never betrays. — After Confucius",
    "Our life is what our thoughts make it. — After Aurelius",
    "How long are you going to wait before you demand the best for yourself? — Epictetus",
    "It's not what happens to you, but how you react to it that matters. — Epictetus",
    "First say to yourself what you would be; then do what you have to do. — Epictetus",
    "No man is free who is not master of himself. — Epictetus",
    "Don't explain your philosophy. Embody it. — After Epictetus",
    "Make the best use of what is in your power, and take the rest as it happens.",
    "Wealth consists not in having great possessions, but in having few wants. — Epictetus",
    "He is a wise man who does not grieve for the things which he has not.",
    "If you want to improve, be content to be thought foolish and stupid. — Epictetus",
    "Only the educated are free. — Epictetus",
    "Attach yourself to what is spiritually superior, regardless of what other people think.",
    "Keep a daily appointment with honesty. The rest of virtue tends to follow.",
    "A short life is long enough if you use it, and too long if you only fear it.",
    "Leave people better than you found them. That is a complete religion of manners.",
    "Measure twice in anger, cut never. Words do not have an undo key.",
    "The house is the first republic. Vote for patience at breakfast.",
    "Enough light to work by is already a kind of wealth.",
    "Do the next right small thing. Grandeur can wait in the hallway.",
    "A calm table feeds more than a clever argument.",
    "Keep your promises in the room where they were made.",
    "Wonder is free. You do not need a throne to feel it.",
    "The day you stop learning, the furniture starts teaching you dust.",
    "Carry water for others when you can. Thirst is a poor ideology.",
    "Let your no be kind and your yes be kept.",
  ],
};

function dayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 1);
  const today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  return Math.round((today.getTime() - start.getTime()) / 86_400_000);
}

export function headerCopyStartIndex(bank: HeaderCopyBank, date?: Date): number {
  if (bank !== "qotd") return 0;
  const items = HEADER_COPY.qotd;
  return dayOfYear(date ?? new Date()) % items.length;
}

export function rotateHeaderCopy(bank: HeaderCopyBank, index: number): string {
  const items = HEADER_COPY[bank];
  return items[Math.abs(index) % items.length];
}
